### ISSUE TITLE
怎么获取当前打开的浏览器名称？

### ISSUE THREAD

**Issue by tangxingjun** [yaniswang/jWebDriver#10]
查看了API，通过driver.info(),能获取到包含浏览器名称的信息，但是我要怎么从里面取出来browserName这个值？

**Comment by tangxingjun** [comment]
已解决，但是现在只能针对配置文件中只有一个浏览器的情况，通过读取配置文件中browers的值来获取，但是不知道如果config.json的broewes配置了多个时，而且在运行到第二、三个浏览器的情况下应该怎么获取当前的浏览器名称

**Comment by yaniswang** [comment]
第二，第三个浏览器是各自并行的，各单个没任何区别。
