### ISSUE TITLE
IE Firefox浏览器执行失败

### ISSUE THREAD

**Issue by gao2q** [yaniswang/jWebDriver#13]
非常感谢您开源的jWebDriver，非常适合做web项目测试。
我按照首页步骤操作后，现在chrome和edge可以使用，但是ie和firefox执行node.js示例脚本时出现错误。

脚本如下
 var JWebDriver = require('jwebdriver');
 var driver = new JWebDriver();
 driver.session("ie")
     .url('https://www.baidu.com/')
     .find('#kw')
     .val('mp3')
     .submit()
     .title()
     .then(function(title){
         console.log(title);
     });

错误日志如下
IE浏览器
(node:13236) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error setting arguments for script
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
System info: host: 'PC016', ip: '192.168.2.78', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: driver.version: unknown
(node:13236) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Firefox浏览器
(node:2992) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Web element reference not seen before: undefined
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
System info: host: 'PC016', ip: '192.168.2.78', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: driver.version: unknown
(node:2992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

我的环境
Windows 10 64bit
IE 11.125.162969.0
Firefox 57.02 64bit
jwebdriver@2.2.5
mocha@4.0.1
selenium-standalone@6.12.0
selenium-server-standalone-3.7.1.jar
2.33-x64-chromedriver
3.7.0-x64-IEDriverServer.exe
0.19.1-x64-geckodriver
16299-MicrosoftEdgeDriver.exe
ie浏览器按照selenium的要求做了权限配置。

我已验证这个环境下，单独使用selenium server能够正常操作各浏览器，我想可以排除selenium server和selenium webdriver的问题。
调查后，我想问题缩小到在jwebdriver这个范围内。
所以想咨询一下，为什么会出现这个问题，jWebDriver对环境（selenium、浏览器等）有什么要求吗？

期待您的回复

**Comment by gao2q** [comment]
当选用IE浏览器时，测试用例执行到.val('mp3')语句执行失败。

调试发现问题出现在elements.js
\npm\node_modules\jwebdriver\lib\elements.js
clear(done){
     this.execCmd('!setElementClear', done);
},

execCmd并没有调用setElementClear，而是调用了setElementSubmit()。

但还不知道如何解决。

**Comment by yaniswang** [comment]
从你描述来看，应该是webdriver底层实现的差异吧？

jwebdriver有个日志选项的，你可以打开看看

![image](https://user-images.githubusercontent.com/970390/34397106-f55b1b66-ebad-11e7-895e-0f40af16074a.png)

如果生成的webdriver命令是完全正确的，那就是驱动层出了问题，或者环境的差异。

**Comment by gao2q** [comment]
感谢。貌似是selemium-server的问题。

执行.find('#kw')时

jwebdriver向selemium发送如下请求 
(internet explorer): 
Executing POST on /session/3d19723f-8adf-4c65-accb-41e0f4dae188/elements

返回了
"{"state":"success","sessionId":null,"hCode":1997374445,"value":[{"element-6066-11e4-a52e-4f735466cecf":"75716d0f-7453-4f93-9d29-05a53fc2f3da"}],"class":"org.openqa.selenium.remote.Response","status":0}"

IE和firefox的情况下，selemium没有正确返回ELEMENT，所以jwebdriver判定没有找到输入框要素。
导致后面出了问题。

**Comment by gao2q** [comment]
改成selenium-server-standalone-3.4.0.jar，问题解决。
请问jwebdriver目前只支持到3.4.0吗？

**Comment by yaniswang** [comment]
应该不会啊，我们是按照webdriver标准API设计的
