### ISSUE TITLE
jWebDriver的attr()方法支持获取哪些属性的内容

### ISSUE THREAD

**Issue by wynanwong** [yaniswang/jWebDriver#4]
![image](https://cloud.githubusercontent.com/assets/10492384/24286094/9545c1e8-10ae-11e7-85a6-f4e6362697f6.png)
上图中用attr()方法可以获取到哪些值，我是想获取content-desc的值的，但是一直获取不了，一直是这个提示：[Error: Not Implemented] not to be an error]

**Comment by yaniswang** [comment]
试试：prop('content-desc')

**Comment by wynanwong** [comment]
很奇怪，用prop()方法，可以获取到例如enabled的值，就是获取不了content-desc的值，一直都是返回null

**Comment by yaniswang** [comment]
https://macacajs.github.io/macaca-wd/

![image](https://cloud.githubusercontent.com/assets/970390/24338260/923e3f3c-12d6-11e7-819a-205ce30c63a2.png)


试试description？

**Comment by yaniswang** [comment]
咋样？可以用吗？

**Comment by wynanwong** [comment]
可以用了，谢谢！
