### ISSUE TITLE
jWebDriver怎么通过cookie方式登录网站？

### ISSUE THREAD

**Issue by wynanwong** [yaniswang/jWebDriver#7]
用UIrecorder录制下来的脚本，因为网站登录是需要验证码的，所以回放肯定是不成功的，就想通过cookie的方式看能不能登录，尝试用driver.cookie('test', '123')方法，发现是不行的。

**Comment by yaniswang** [comment]
估计是你写的cookie不够完整，或者写的域写错了

**Comment by wynanwong** [comment]
用百度登录的例子，我用jmeter是成功的：
![jmeter](https://cloud.githubusercontent.com/assets/10492384/25787486/5656306e-33d4-11e7-8518-a8a42ce45631.png)

代码里面是这样的：
![code](https://cloud.githubusercontent.com/assets/10492384/25787490/6343bad0-33d4-11e7-991d-0d8a651483ce.png)

然后server端的log是这样：
![serverlog](https://cloud.githubusercontent.com/assets/10492384/25787498/72402654-33d4-11e7-8669-d5a060280e35.png)

**Comment by yaniswang** [comment]
那可能就是时间点不正确，你在webdriver中写cookie可能是不是晚了？

**Comment by wynanwong** [comment]
看server端的log信息时先执行addCookie，再访问百度的，这个是在访问之前就写入，按理说不会晚的。

**Comment by yaniswang** [comment]
知道原因了，是因为你写错域了。

webdriver的写cookie功能依赖当前所在的网页域名，你在a.com无法写cookie到b.com

实际上内部的逻辑还是依赖于浏览器所在的环境。

**Comment by wynanwong** [comment]
明白了，就是需要先到所访问的页面，再加cookie，试了一下是可以的。

**Comment by luoxi001713** [comment]
@wynanwong 借楼问下，这个是怎么实现的？
以下是我的代码，录制完之后，增加了driver.cookie行，没做其他改动，还需要改动哪里么？
`
   before(function(){
        let self = this;
        driver = self.driver;
        testVars = self.testVars;
        driver.cookie('COFFEE_TOKEN','e3fda14-dc05-46e5-b120-9a94900b12',{domain:''});
    });
`
